import { Conditional } from "components/Conditional";
import { Counter } from "components/Counter";
import { LoginForm } from "components/LoginForm/LoginForm";
import { TestForm } from "components/TestForm/TestForm";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

interface Props {
  data?: HomeData[];
}

const Home: NextPage<Props> = ({ data }: Props) => {
  // console.log(data);
  // console.log(data.length.toLocaleString("bn-BD"));

  return (
    <>
      <Head>
        <title>Test - Jest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h1 id="test-jest">Test Next Jest</h1>

        <Counter />

        <Conditional />

        <LoginForm />

        <TestForm />
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL);
  const data: HomeData[] = await res.json();

  // console.log("data: ", data);

  return {
    props: {
      data: data,
    },
  };
};

export default Home;
